version: 2.1

jobs:
  python:
    environment:
      FOO: bar
    docker:
      - image: cimg/python:3.9
    steps:
      - run:
          name: print FOO
          shell: '/usr/bin/env python'
          command: |
            import os
            print(os.environ["FOO"])
  ruby:
    environment:
      FOO: bar
    docker:
      - image: cimg/ruby:2.7
    steps:
      - run:
          name: print FOO
          shell: '/usr/bin/env ruby'
          command: |
            puts ENV["FOO"]
  node:
    environment:
      FOO: bar
    docker:
      - image: cimg/node:17.9
    steps:
      - run: |
          echo $HOME/.node_modules
      - run:
          name: print FOO
          shell: '/usr/bin/env node -i'
          command: |
            node -i
            console.log('FOO');

  bash:
    environment:
      FOO: bar
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: print FOO
          shell: '/usr/bin/env bash'
          command: |
            printenv FOO

workflows:
  taco-shells:
    jobs:
      - ruby
      - python
      - bash
      - node
